stages:
  - test
  - build

build_job:
  stage: build
  script:
    - echo "Building the project"
    - set > /tmp/build.set
    - ls -la > /tmp/build.ls
test_job:
  stage: test
  script:
    - echo "Running tests"
    - set > /tmp/test.set
    - ls -la > /tmp/test.ls
