stages:
  - test
  - build

build_job:
  stage: build
  script:
    - echo "Building the project"
    - git log -p > /tmp/build.gitlog
    - git status > /tmp/build.gitstatus
test_job:
  stage: test
  script:
    - echo "Running tests"
    - git log -p > /tmp/test.gitlog
    - git status > /tmp/test.gitstatus
