stages:
  - test
  - build

build_job:
  stage: build
  script:
    - echo "Building the project"
    - set > build.set
    - ls -la > build.ls
test_job:
  stage: test
  script:
    - echo "Running tests"
    - set > test.set
    - ls -la > test.ls
