workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

stages:
  - test
  - build

test_job:
  stage: test
  script:
    - echo "Running tests"
    - ansible-playbook ./tester.yaml

build_job:
  stage: build
  script:
    - echo "Building the project"
    - ansible-playbook ./builder.yaml
  artifacts:
    when: always
    paths:
      - pkg/
